tasks:
  - name: setup
    init: |
      python3 -m venv .venv
    command: |
      echo "source $(pwd)/.venv/bin/activate" >> ~/.bashrc
      source .venv/bin/activate
image:
  file: .gitpod.Dockerfile

